sf2web:
  image: nginx
  volumes:
   - /Users/killerwolf/git/docker-symfony2/www:/var/www/application
   - /Users/killerwolf/git/docker-symfony2/docker/nginx:/etc/nginx/conf.d
  links:
   - sf2db
   - sf2phpfpm
   - sf2phpcli
  ports:
   - "80:80"
sf2db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: root
sf2phpfpm:
  image: php:fpm
  volumes:
   - /Users/killerwolf/git/docker-symfony2/www:/var/www/application
   - /Users/killerwolf/git/docker-symfony2/docker/php:/usr/local/etc/php/conf.d
  volumes_from:
   - sf2data
sf2phpcli:
  image: php:cli
  volumes:
   - /Users/killerwolf/git/docker-symfony2/www:/var/www/application
   - /Users/killerwolf/git/docker-symfony2/docker/php:/usr/local/etc/php/conf.d
sf2data:
  image: busybox
  volumes:
    - /var/www/application/app/cache
    - /var/www/application/app/logs